### ISSUE TITLE
Compatibility Inquiry: Pericia DataExport with .NET 8

### ISSUE THREAD

**Issue by daniloctdev** [pericia/Pericia.DataExport#38]
Overview:
In the ongoing development and maintenance of our software suite, a critical aspect involves the integration of Pericia DataExport. Following recent updates where package upgrades were performed, a notable issue has arisen specifically related to its compatibility with .NET 8.

Problem Statement:
Post the recent package updates, there has been a discernible disruption in the functionality of Pericia DataExport. The software ceases to function as intended after these updates are applied. This issue surfaces primarily when working within the .NET 8 environment.

Requested Clarification:
Our team seeks comprehensive information or guidance regarding the compatibility status of Pericia DataExport with the .NET 8 framework. Understanding the compatibility nuances, potential workarounds, or necessary adjustments to ensure seamless functionality within the .NET 8 ecosystem is imperative.

Steps Taken:
Package Updates: The issue was noticed subsequent to recent updates applied to various packages within our software stack.
Testing Environment: Multiple testing scenarios were conducted to isolate the issue, consistently observing the disruption in Pericia DataExport functionality within .NET 8.
Details:
Software Environment: .NET 8 framework.

Expected Outcome:
The primary goal of this inquiry is to determine the compatibility status between Pericia DataExport and .NET 8, thereby ensuring seamless integration and functionality within our software suite.

Additional Information:
Any additional insights, advice, or alternative approaches that can facilitate the resolution of this compatibility issue would be greatly appreciated.

This GitHub issue is initiated to collaborate, investigate, and resolve the compatibility concerns between Pericia DataExport and .NET 8. All contributions, suggestions, or findings are welcomed and will be duly acknowledged.

Thank you for your attention to this matter.

**Comment by glacasa** [comment]
Hi,

You use a lot of what seem to be corporate language, as a non-native english speaker, I may have misunderstood some parts of your message, sorry if it's the case.

I have not used this package in .NET 8 yet, so I don't know what would be the cause of the problem.

One thing you may check : the code uses a lot of reflection, I'm pretty sure this would break with AOT/tree-shaking.
Maybe this is something you have enabled during the .NET upgrade ?

**Comment by daniloctdev** [comment]
Hi, I've done several tests
I tried to update package by package and I think the problem is not with .net8 but with the dependency of DocumentFormat.OpenXml

I get this error:
![image](https://github.com/pericia/Pericia.DataExport/assets/107484701/0862b880-e17c-4c61-8028-5dafcd33803d)

DocumentFormat.OpenXml version 3.0.0

**Comment by glacasa** [comment]
According to https://github.com/dotnet/Open-XML-SDK, we may have some breaking changes with version 3.0

> NOTICE:

>    [v3.0.0](https://www.nuget.org/packages/DocumentFormat.OpenXml/3.0.0) refactors and addresses some technical debt while retaining source compatibility as much as possible. You should be able to update your package and recompile with limited changes. However, binary compatibility was not a goal and will break that for some changes which are documented. PRs that introduced such changes are marked with a breaking-change label and were added to a list to help migrating to v3.0.0.

>    Please see the [v3.0.0 milestone](https://github.com/OfficeDev/Open-XML-SDK/milestone/1) for issues and PRs that are included. For discussions, please join us at https://github.com/OfficeDev/Open-XML-SDK/issues/1270.

Can you try downgrading to last 2.x version and confirm if it works again ?

I may have to update the code to be able to use version 3

**Comment by daniloctdev** [comment]
yes, work 2.20
![image](https://github.com/pericia/Pericia.DataExport/assets/107484701/910c8a46-cecd-4d2b-b8e0-b3abfdcd0983)

**Comment by glacasa** [comment]
I am able to reproduce the exception, when the OpenXml reference is different.

I have rebuilt with 3.0.0 reference, it should now work better. Let me know if it fixes your problem :
https://www.nuget.org/packages/Pericia.DataExport/2.0.0

**Comment by daniloctdev** [comment]
thanks. It's working now.

you can insert the dependency of DocumentFormat.OpenXml >= 3 as required for pericia 2.0. 
I had to manually update the dependency.
